main: io.github.stonley890.pausechat.PauseChat
name: PauseChat
version: 1.0.2
api-version: 1.19
description: A Spigot plugin that temporarily (or permanently) disables Minecraft chat.
author: Stonley890