main: org.macver.pausechat.PauseChat
name: PauseChat
version: "${project.version}"
api-version: 1.19
description: A Spigot plugin that temporarily (or permanently) disables Minecraft chat.
author: BogTheMudWing